<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script defer src="/JS/login.js"></script>
</head>
    <nav>

    </nav>
    <body class="container">
        <h1 class="text-center my-3">Welcome to Fish Food</h1>
        <h3 class="text-center my-3">Please Log In</h3>
        <section class="form-group justify-content-center d-flex my-5">
            <form method="POST">
                <input type="text" class="form-control my-3" id="emailInput" name="email" placholde="Enter email here" />
                <small class="form-text text-muted mb-3">If this is your first visit a new account will be created</small>
                <button id="loginBtn" class="btn btn-secondary" type="submit">Submit</button>
            </form>
        </section>
        <div class="loginMessage text-center text-danger">
        </div> 
    </body>
</html>